from enum import Enum


class TipoSuporte(str, Enum):
    FISICO = "FISICO"
    DIGITAL = "DIGITAL"
    HIBRIDO = "HIBRIDO"


class TipoUnidade(str, Enum):
    CAIXA = "CAIXA"
    PASTA = "PASTA"
    VOLUME = "VOLUME"
    AIP = "AIP"
    SIP = "SIP"
    DIP = "DIP"


class NivelAcesso(str, Enum):
    PUBLICO = "PUBLICO"
    RESTRITO = "RESTRITO"
    CONFIDENCIAL = "CONFIDENCIAL"


class StatusUnidade(str, Enum):
    ATIVA = "ATIVA"
    INATIVA = "INATIVA"
    TRANSFERIDA = "TRANSFERIDA"
    ELIMINADA = "ELIMINADA"


class TipoMidiaArmazenamento(str, Enum):
    FILESYSTEM = "FILESYSTEM"
    NAS = "NAS"
    NFS = "NFS"
    LTO = "LTO"
    S3 = "S3"
    CLOUD = "CLOUD"


class FuncaoCopia(str, Enum):
    PRESERVACAO = "PRESERVACAO"
    BACKUP = "BACKUP"
    ACESSO = "ACESSO"
    QUARENTENA = "QUARENTENA"


class StatusCopia(str, Enum):
    ATIVA = "ATIVA"
    INDISPONIVEL = "INDISPONIVEL"
    CORROMPIDA = "CORROMPIDA"
    EM_VERIFICACAO = "EM_VERIFICACAO"


class TipoEventoPreservacao(str, Enum):
    INGESTAO = "INGESTAO"
    VALIDACAO = "VALIDACAO"
    FIXIDEZ = "FIXIDEZ"
    REPLICACAO = "REPLICACAO"
    MIGRACAO = "MIGRACAO"
    ACESSO = "ACESSO"
    MOVIMENTACAO = "MOVIMENTACAO"
    OUTRO = "OUTRO"


class ResultadoEventoPreservacao(str, Enum):
    SUCESSO = "SUCESSO"
    FALHA = "FALHA"
    ALERTA = "ALERTA"
    INDETERMINADO = "INDETERMINADO"


class TipoInstrumentoPesquisa(str, Enum):
    GUIA = "GUIA"
    INVENTARIO = "INVENTARIO"
    CATALOGO = "CATALOGO"
    INDICE = "INDICE"
    BASE_TEMATICA = "BASE_TEMATICA"
    EXPOSICAO = "EXPOSICAO"
    OUTRO = "OUTRO"


class StatusInstrumentoPesquisa(str, Enum):
    RASCUNHO = "RASCUNHO"
    PUBLICADO = "PUBLICADO"
    ARQUIVADO = "ARQUIVADO"


class VisibilidadeInstrumentoPesquisa(str, Enum):
    INTERNO = "INTERNO"
    PUBLICO = "PUBLICO"
    RESTRITO = "RESTRITO"


class TipoCampoInstrumento(str, Enum):
    TEXTO_CURTO = "TEXTO_CURTO"
    TEXTO_LONGO = "TEXTO_LONGO"
    NUMERO = "NUMERO"
    DATA = "DATA"
    PERIODO = "PERIODO"
    BOOLEANO = "BOOLEANO"
    LISTA_SIMPLES = "LISTA_SIMPLES"
    LISTA_MULTIPLA = "LISTA_MULTIPLA"
    VOCABULARIO = "VOCABULARIO"
    UNIDADE_ACONDICIONAMENTO = "UNIDADE_ACONDICIONAMENTO"
    REGISTRO_DESCRITIVO = "REGISTRO_DESCRITIVO"
    URL = "URL"
    ARQUIVO = "ARQUIVO"
    IMAGEM = "IMAGEM"
    CAMPO_CALCULADO = "CAMPO_CALCULADO"


class TipoLocalGuarda(str, Enum):
    DEPOSITO = "DEPOSITO"
    SALA_COFRE = "SALA_COFRE"
    DATA_CENTER = "DATA_CENTER"
    MAPOTECA = "MAPOTECA"
    LABORATORIO = "LABORATORIO"
    NUVEM = "NUVEM"
    OUTRO = "OUTRO"


class TipoZonaGuarda(str, Enum):
    ACERVO_TEXTUAL = "ACERVO_TEXTUAL"
    CARTOGRAFICO = "CARTOGRAFICO"
    ICONOGRAFICO = "ICONOGRAFICO"
    MIDIAS_REMOVIVEIS = "MIDIAS_REMOVIVEIS"
    FITAS_LTO = "FITAS_LTO"
    STORAGE_ONLINE = "STORAGE_ONLINE"
    QUARENTENA = "QUARENTENA"
    BACKUP = "BACKUP"
    ACESSO = "ACESSO"
    OUTRO = "OUTRO"


class TipoEstruturaArmazenamento(str, Enum):
    ESTANTE = "ESTANTE"
    ARQUIVO_DESLIZANTE = "ARQUIVO_DESLIZANTE"
    MAPOTECA = "MAPOTECA"
    GAVETEIRO = "GAVETEIRO"
    ARMARIO = "ARMARIO"
    RACK = "RACK"
    COFRE = "COFRE"
    SERVIDOR = "SERVIDOR"
    NAS = "NAS"
    BUCKET_S3 = "BUCKET_S3"
    VOLUME_REDE = "VOLUME_REDE"
    UNIDADE_LTO = "UNIDADE_LTO"
    OUTRO = "OUTRO"


class TipoCompartimentoArmazenamento(str, Enum):
    PRATELEIRA = "PRATELEIRA"
    GAVETA = "GAVETA"
    BANDEJA = "BANDEJA"
    SLOT = "SLOT"
    VOLUME = "VOLUME"
    DIRETORIO = "DIRETORIO"
    BUCKET = "BUCKET"
    PARTICAO = "PARTICAO"
    CAIXA_INTERNA = "CAIXA_INTERNA"
    OUTRO = "OUTRO"


class TipoPosicaoArmazenamento(str, Enum):
    POSICAO_CAIXA = "POSICAO_CAIXA"
    POSICAO_PASTA = "POSICAO_PASTA"
    POSICAO_VOLUME = "POSICAO_VOLUME"
    POSICAO_MAPA = "POSICAO_MAPA"
    SLOT_FITA = "SLOT_FITA"
    SLOT_MIDIA = "SLOT_MIDIA"
    DIRETORIO_AIP = "DIRETORIO_AIP"
    DIRETORIO_SIP = "DIRETORIO_SIP"
    DIRETORIO_DIP = "DIRETORIO_DIP"
    BUCKET_OBJETO = "BUCKET_OBJETO"
    VOLUME_LOGICO = "VOLUME_LOGICO"
    OUTRO = "OUTRO"
