apiVersion: apps/v1
kind: Deployment
metadata:
  name: thor-pesquisador-backend
spec:
  template:
    spec:
      containers:
        - name: thor-pesquisador-backend
          env:
            - name: GOVBR_DEV_LOGIN
              value: "true"
