apiVersion: apps/v1
kind: Deployment
metadata:
  name: thor-pesquisador-backend
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thor-pesquisador-frontend
spec:
  replicas: 2
