apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres.yaml
  - mongo.yaml
  - redis.yaml
  - meilisearch.yaml
  - backend.yaml
  - index-worker.yaml
  - frontend.yaml
  - routes.yaml
configMapGenerator:
  - name: thor-pesquisador-config
    literals:
      - APP_ENV=dev
      - PUBLIC_APP_URL=https://thor-pesquisador.apps.example.local
      - GOVBR_AUTHORIZE_URL=https://sso.staging.acesso.gov.br/authorize
      - GOVBR_TOKEN_URL=https://sso.staging.acesso.gov.br/token
      - GOVBR_JWKS_URL=https://sso.staging.acesso.gov.br/jwk
      - GOVBR_REDIRECT_URI=https://thor-pesquisador-api.apps.example.local/api/v1/auth/govbr/callback
      - CORS_ORIGINS=["https://thor-pesquisador.apps.example.local"]
      - MONGODB_DATABASE=thor_pesquisador
      - GOVBR_DEV_LOGIN=false
      - REDIS_URL=redis://thor-pesquisador-redis:6379/0
      - INDEXACAO_QUEUE_NAME=thor_pesquisador:indexacao
      - MEILISEARCH_URL=http://thor-pesquisador-meilisearch:7700
      - INDEXACAO_BATCH_SIZE=500
secretGenerator:
  - name: thor-pesquisador-secrets
    literals:
      - DATABASE_URL=postgresql+psycopg://thor:thor@thor-pesquisador-postgres:5432/thor_pesquisador
      - MONGODB_URL=mongodb://thor-pesquisador-mongo:27017/thor_pesquisador
      - MEILISEARCH_API_KEY=change-me-dev-master-key
      - GOVBR_CLIENT_ID=change-me
      - GOVBR_CLIENT_SECRET=change-me
      - APP_SESSION_SECRET=change-me
generatorOptions:
  disableNameSuffixHash: true
