apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thor-pesquisador-mongo
spec:
  serviceName: thor-pesquisador-mongo
  replicas: 1
  selector:
    matchLabels:
      app: thor-pesquisador-mongo
  template:
    metadata:
      labels:
        app: thor-pesquisador-mongo
    spec:
      containers:
        - name: thor-pesquisador-mongo
          image: mongo:7
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: data
              mountPath: /data/db
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: thor-pesquisador-mongo
spec:
  selector:
    app: thor-pesquisador-mongo
  ports:
    - port: 27017
      targetPort: 27017
