apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: thor-pesquisador-frontend
spec:
  to:
    kind: Service
    name: thor-pesquisador-frontend
  port:
    targetPort: 3000
  tls:
    termination: edge
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: thor-pesquisador-backend
spec:
  to:
    kind: Service
    name: thor-pesquisador-backend
  port:
    targetPort: 8000
  tls:
    termination: edge
